import mech1 from '../assets/images/mech1.jpg';
import mech2 from '../assets/images/mech2.jpg';
import mech3 from '../assets/images/mech3.jpg';
import mech4 from '../assets/images/mech4.jpg';
import mech5 from '../assets/images/mech5.jpg';
import mech6 from '../assets/images/mech6.jpg';
import mech7 from '../assets/images/mech7.jpg';
import mech8 from '../assets/images/mech8.jpg';
import mech9 from '../assets/images/mech9.jpg';
import mech10 from '../assets/images/mech10.jpg';


const Mechanic = [
    {
      _id: '1',
      name: 'Ahmed Khan',
      location: 'Line 10, Street 7B, Hostel City, Islamabad',
      phoneNumber: '+92 300 1234567',
      timingFrom: '9:00 AM',
      timingTo: '6:00 PM',
      experience: '5 years',
      rating: 4.5,
      image: mech1,
    },
    {
      _id: '2',
      name: 'Zahid Malik',
      location: 'Street 12, Sector G-11, Islamabad',
      phoneNumber: '+92 301 7654321',
      timingFrom: '8:00 AM',
      timingTo: '5:00 PM',
      experience: '8 years',
      rating: 4.7,
      image: mech2,
    },
    {
      _id: '3',
      name: 'Aslam Iqbal',
      location: 'House 23, Street 19, F-8, Islamabad',
      phoneNumber: '+92 312 4567890',
      timingFrom: '10:00 AM',
      timingTo: '7:00 PM',
      experience: '10 years',
      rating: 4.9,
      image: mech3,
    },
    {
      _id: '4',
      name: 'Bilal Ahmed',
      location: 'Sector H-9, Islamabad',
      phoneNumber: '+92 345 2345678',
      timingFrom: '7:00 AM',
      timingTo: '4:00 PM',
      experience: '7 years',
      rating: 4.2,
      image: mech4,
    },
    {
      _id: '5',
      name: 'Kamran Ali',
      location: 'Sector G-10/4, Islamabad',
      phoneNumber: '+92 333 7890123',
      timingFrom: '11:00 AM',
      timingTo: '8:00 PM',
      experience: '6 years',
      rating: 4.4,
      image: mech5,
    },
    {
      _id: '6',
      name: 'Farooq Baig',
      location: 'Street 3, Sector F-6/1, Islamabad',
      phoneNumber: '+92 320 9876543',
      timingFrom: '6:00 AM',
      timingTo: '3:00 PM',
      experience: '12 years',
      rating: 4.6,
      image: mech6,
    },
    {
      _id: '7',
      name: 'Tariq Hussain',
      location: 'House 10, Street 25, I-8/3, Islamabad',
      phoneNumber: '+92 315 6543210',
      timingFrom: '9:30 AM',
      timingTo: '6:30 PM',
      experience: '4 years',
      rating: 4.1,
      image: mech7,
    },
    {
      _id: '8',
      name: 'Naveed Akhtar',
      location: 'Street 15, Sector F-10/2, Islamabad',
      phoneNumber: '+92 313 2109876',
      timingFrom: '8:30 AM',
      timingTo: '5:30 PM',
      experience: '9 years',
      rating: 4.8,
      image: mech8,
    },
    {
      _id: '9',
      name: 'Rizwan Qureshi',
      location: 'Sector G-9, Islamabad',
      phoneNumber: '+92 321 8765432',
      timingFrom: '10:00 AM',
      timingTo: '7:00 PM',
      experience: '3 years',
      rating: 4.0,
      image: mech9,
    },
    {
      _id: '10',
      name: 'Shahbaz Haider',
      location: 'House 50, Street 12, F-7/4, Islamabad',
      phoneNumber: '+92 330 5432109',
      timingFrom: '7:30 AM',
      timingTo: '4:30 PM',
      experience: '11 years',
      rating: 4.7,
      image: mech10,
    },
    {
      _id: '11',
      name: 'Faheem Javed',
      location: 'Street 11, Sector I-10/3, Islamabad',
      phoneNumber: '+92 302 1238907',
      timingFrom: '9:00 AM',
      timingTo: '6:00 PM',
      experience: '5 years',
      rating: 4.3,
      image: mech1,
    },
    {
      _id: '12',
      name: 'Imran Khan',
      location: 'Sector G-6/4, Islamabad',
      phoneNumber: '+92 311 4562341',
      timingFrom: '8:00 AM',
      timingTo: '5:00 PM',
      experience: '8 years',
      rating: 4.9,
      image: mech2,
    },
    {
      _id: '13',
      name: 'Rafay Sultan',
      location: 'Street 20, Sector E-7, Islamabad',
      phoneNumber: '+92 300 2341235',
      timingFrom: '6:00 AM',
      timingTo: '3:00 PM',
      experience: '7 years',
      rating: 4.6,
      image: mech3,
    },
    {
      _id: '14',
      name: 'Sajid Sheikh',
      location: 'House 18, Street 40, F-6, Islamabad',
      phoneNumber: '+92 317 7654321',
      timingFrom: '7:00 AM',
      timingTo: '4:00 PM',
      experience: '13 years',
      rating: 4.8,
      image: mech4,
    },
    {
      _id: '15',
      name: 'Omar Farooq',
      location: 'Sector I-9, Islamabad',
      phoneNumber: '+92 315 9081234',
      timingFrom: '9:00 AM',
      timingTo: '6:00 PM',
      experience: '6 years',
      rating: 4.8,
      image: mech5,
    },
    // Add mechanics from 16 to 30 in a similar format
  ];
  
  export default Mechanic;
  